# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.3

EAPI="3"
SUPPORT_PYTHON_ABIS="1"
DISTUTILS_SRC_TEST="setup.py"

inherit distutils


DESCRIPTION="Autobahn|Python provides WebSocket and WAMP for Twisted and Asyncio"
HOMEPAGE="http://autobahn.ws/python"
SRC_URI="https://pypi.python.org/packages/source/a/autobahn/${P}.zip"

LICENSE="Apache-2.0"
KEYWORDS="~amd64"
SLOT="0"
IUSE="accelerate asyncio compress serialization twisted"

DEPEND="dev-python/setuptools"
RDEPEND=">=dev-python/six-1.6.1
	accelerate? ( >=dev-python/ujson-1.33 )
	accelerate? ( >=dev-python/wsaccel-0.6.2 )
	asyncio? ( >=dev-python/futures-2.1.5 )
	asyncio? ( >=dev-python/trollius-0.1.2 )
	compress? ( >=dev-python/lz4-0.2.1 )
	compress? ( >=dev-python/python-snappy-0.5 )
	dev-python/setuptools
	serialization? ( >=dev-python/msgpack-python-0.4.0 )
	twisted? ( >=dev-python/twisted-core-11.1 )"


