# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.3

EAPI="3"
SUPPORT_PYTHON_ABIS="1"

inherit distutils


DESCRIPTION="Pythonic argument parser, that will make you smile"
HOMEPAGE="http://docopt.org"
SRC_URI="https://pypi.python.org/packages/source/d/docopt/${P}.tar.gz"

LICENSE="MIT"
KEYWORDS="~amd64"
SLOT="0"
IUSE="examples"

DEPEND="dev-python/setuptools"
RDEPEND="${DEPEND}"


src_install() {
	distutils_src_install
	if use examples; then
		insinto /usr/share/doc/"${PF}"/
		doins -r examples
	fi
}
