# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.3

EAPI="3"
SUPPORT_PYTHON_ABIS="1"

inherit distutils


DESCRIPTION="Python REPL build on top of prompt_toolkit"
HOMEPAGE="https://github.com/jonathanslenders/ptpython"
SRC_URI="https://pypi.python.org/packages/source/p/ptpython/${P}.tar.gz"

LICENSE=""
KEYWORDS="~amd64"
SLOT="0"
IUSE=""

DEPEND="dev-python/setuptools"
RDEPEND="=dev-python/prompt_toolkit-0.30
	>=dev-python/jedi-0.8.1
	dev-python/docopt
	dev-python/setuptools"


